### ISSUE TITLE
Is this usable? 

### ISSUE THREAD

**Issue by srid** [Compositional/servant-client-jsaddle#7]
Currently tripping up on missing cabal dependency `servant-client-js` which doesn't seem to exist anywhere. 

cf. https://github.com/Compositional/reflex-servant/issues/6

I wish there was a simple Reflex example for this set of libraries!

**Comment by roberth** [comment]
Yes, this is usable. I've fixed the dependency. It was supposed to be a self reference, but apparently I forgot to change it when renaming the library from js to jsaddle.

I agree that we should have a full example of the Reflex stuff, but not in this repo.
