### ISSUE TITLE
Relationship to servant-jsaddle?

### ISSUE THREAD

**Issue by niteria** [Compositional/servant-client-jsaddle#8]
Hi,

I wanted to use this library, but browsing around I got a little confused.
If I understand correctly https://github.com/haskell-servant/servant-jsaddle is a direct fork of this and seems to have been updated more recently.

Is this fork also active or has it been deprecated?
If it's deprecated would you mind if I send a pull request that points to the fork?

Thanks,
Bartosz

**Comment by roberth** [comment]
Thanks! I've updated the readme to explain that it has moved.
